const { Router } = require('express')
const router = new Router()

// ─── Импорты роутеров ─────────────────────────────────────
const userRouter = require('./userRouter')
const chartsRouter = require('./chartsRouter')
const valveRouter = require('./valveRouter')
const greenhouseRouter = require('./greenhouseRouter')
const tankRouter = require('./tankRouter')
const tankPurposeRouter = require('./tankPurposeRouter')
const additiveRouter = require('./additiveRouter')
const solutionHistoryRouter = require('./solutionHistoryRouter')
const solutionCompositionRouter = require('./solutionCompositionRouter')
const wateringHistoryRouter = require('./wateringHistoryRouter')
const dailyConditionRouter = require('./dailyConditionRouter')
const drainHistoryRouter = require('./drainHistoryRouter')
const generatorRouter = require('./generatorRouter')
const wateringScheduleRouter = require('./wateringScheduleRouter')

// ─── Подключение. Пути слева — то, что ждёт клиент. ──────
router.use('/user', userRouter)
router.use('/charts', chartsRouter)
router.use('/valve', valveRouter)
router.use('/greenhouse', greenhouseRouter)
router.use('/tank', tankRouter)
router.use('/tank-purpose', tankPurposeRouter)
router.use('/additive', additiveRouter)
router.use('/solution', solutionHistoryRouter)
router.use('/solution-composition', solutionCompositionRouter)
router.use('/watering', wateringHistoryRouter)
router.use('/condition', dailyConditionRouter)
router.use('/drain', drainHistoryRouter)
router.use('/generators', generatorRouter)
router.use('/watering-schedule', wateringScheduleRouter)

module.exports = router