name: Registration CI

on:
  push:
    branches: [ main, master, back_kate ]
  pull_request:
    branches: [ main, master, back_kate ]

jobs:
  test-registration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json # Удалите, если package.json в корне

      - name: Install dependencies
        run: npm ci

      - name: Run registration tests
        run: npx jest test/test-registration.js --runInBand
        env:
          SECRET_KEY: test-secret-key